services:
  db:
    image: postgres:16
    container_name: jobtracker-db
    environment:
      POSTGRES_DB: jobtracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - jobtracker_pg:/var/lib/postgresql/data

volumes:
  jobtracker_pg:
